FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist/angular-console-demo-with-docker-compose /usr/share/nginx/html

EXPOSE 80
